//
//  CountryInfo.swift
//  iacademy
//
//  Created by Marwan Osama on 24/01/2026.
//

import Foundation

struct CountryInfo {
    let countryCode: String
    let phoneCode: String
    let arabicName: String
}

extension CountryInfo {
    
    static let countries: [CountryInfo] = [
        CountryInfo(countryCode: "IE", phoneCode: "+353", arabicName: "آيرلندا"),
        CountryInfo(countryCode: "IS", phoneCode: "+354", arabicName: "آيسلندا"),
        CountryInfo(countryCode: "AZ", phoneCode: "+994", arabicName: "أذربيجان"),
        CountryInfo(countryCode: "AM", phoneCode: "+374", arabicName: "أرمينيا"),
        CountryInfo(countryCode: "AW", phoneCode: "+297", arabicName: "أروبا"),
        CountryInfo(countryCode: "AU", phoneCode: "+61", arabicName: "أستراليا"),
        CountryInfo(countryCode: "AF", phoneCode: "+93", arabicName: "أفغانستان"),
        CountryInfo(countryCode: "AL", phoneCode: "+355", arabicName: "ألبانيا"),
        CountryInfo(countryCode: "DE", phoneCode: "+49", arabicName: "ألمانيا"),
        CountryInfo(countryCode: "AG", phoneCode: "+1-268", arabicName: "أنتيغوا وبربودا"),
        CountryInfo(countryCode: "AD", phoneCode: "+376", arabicName: "أندورا"),
        CountryInfo(countryCode: "AO", phoneCode: "+244", arabicName: "أنغولا"),
        CountryInfo(countryCode: "AI", phoneCode: "+1-264", arabicName: "أنغيلا"),
        CountryInfo(countryCode: "UY", phoneCode: "+598", arabicName: "أوروغواي"),
        CountryInfo(countryCode: "UZ", phoneCode: "+998", arabicName: "أوزبكستان"),
        CountryInfo(countryCode: "UG", phoneCode: "+256", arabicName: "أوغندا"),
        CountryInfo(countryCode: "UA", phoneCode: "+380", arabicName: "أوكرانيا"),
        CountryInfo(countryCode: "ET", phoneCode: "+251", arabicName: "إثيوبيا"),
        CountryInfo(countryCode: "ER", phoneCode: "+291", arabicName: "إريتريا"),
        CountryInfo(countryCode: "ES", phoneCode: "+34", arabicName: "إسبانيا"),
        CountryInfo(countryCode: "EE", phoneCode: "+372", arabicName: "إستونيا"),
        CountryInfo(countryCode: "IL", phoneCode: "+972", arabicName: "إسرائيل"),
        CountryInfo(countryCode: "IO", phoneCode: "+246", arabicName: "إقليم المحيط البريطاني الهندي"),
        CountryInfo(countryCode: "EC", phoneCode: "+593", arabicName: "إكوادور"),
        CountryInfo(countryCode: "ID", phoneCode: "+62", arabicName: "إندونيسيا"),
        CountryInfo(countryCode: "IR", phoneCode: "+98", arabicName: "إيران"),
        CountryInfo(countryCode: "IT", phoneCode: "+39", arabicName: "إيطاليا"),
        CountryInfo(countryCode: "AR", phoneCode: "+54", arabicName: "الأرجنتين"),
        CountryInfo(countryCode: "JO", phoneCode: "+962", arabicName: "الأردن"),
        CountryInfo(countryCode: "GL", phoneCode: "+299", arabicName: "الأرض الخضراء"),
        CountryInfo(countryCode: "TF", phoneCode: "+262", arabicName: "الأراضي الفرنسية الجنوبية والقطبية"),
        CountryInfo(countryCode: "AE", phoneCode: "+971", arabicName: "الإمارات العربيّة المتحدة"),
        CountryInfo(countryCode: "RU", phoneCode: "+7", arabicName: "الاتحاد الروسي"),
        CountryInfo(countryCode: "BH", phoneCode: "+973", arabicName: "البحرين"),
        CountryInfo(countryCode: "BR", phoneCode: "+55", arabicName: "البرازيل"),
        CountryInfo(countryCode: "PT", phoneCode: "+351", arabicName: "البرتغال"),
        CountryInfo(countryCode: "BA", phoneCode: "+387", arabicName: "البوسنة والهرسك"),
        CountryInfo(countryCode: "ME", phoneCode: "+382", arabicName: "الجبل الأسود"),
        CountryInfo(countryCode: "DZ", phoneCode: "+213", arabicName: "الجزائر"),
        CountryInfo(countryCode: "DK", phoneCode: "+45", arabicName: "الدنمارك"),
        CountryInfo(countryCode: "SV", phoneCode: "+503", arabicName: "السلفادور"),
        CountryInfo(countryCode: "SN", phoneCode: "+221", arabicName: "السنغال"),
        CountryInfo(countryCode: "SD", phoneCode: "+249", arabicName: "السودان"),
        CountryInfo(countryCode: "SE", phoneCode: "+46", arabicName: "السويد"),
        CountryInfo(countryCode: "SO", phoneCode: "+252", arabicName: "الصومال"),
        CountryInfo(countryCode: "CN", phoneCode: "+86", arabicName: "الصين"),
        CountryInfo(countryCode: "EH", phoneCode: "+212", arabicName: "الصحراء الغربية"),
        CountryInfo(countryCode: "IQ", phoneCode: "+964", arabicName: "العراق"),
        CountryInfo(countryCode: "VA", phoneCode: "+379", arabicName: "الفاتيكان"),
        CountryInfo(countryCode: "PH", phoneCode: "+63", arabicName: "الفلبين"),
        CountryInfo(countryCode: "AQ", phoneCode: "+672", arabicName: "القارة القطبية الجنوبية"),
        CountryInfo(countryCode: "SX", phoneCode: "+1-721", arabicName: "سانت مارتن"),
        CountryInfo(countryCode: "CM", phoneCode: "+237", arabicName: "الكاميرون"),
        CountryInfo(countryCode: "CG", phoneCode: "+242", arabicName: "الكونغو"),
        CountryInfo(countryCode: "KW", phoneCode: "+965", arabicName: "الكويت"),
        CountryInfo(countryCode: "MA", phoneCode: "+212", arabicName: "المغرب"),
        CountryInfo(countryCode: "MX", phoneCode: "+52", arabicName: "المكسيك"),
        CountryInfo(countryCode: "SA", phoneCode: "+966", arabicName: "المملكة العربيّة السعوديّة"),
        CountryInfo(countryCode: "GB", phoneCode: "+44", arabicName: "المملكة المتحدة"),
        CountryInfo(countryCode: "NO", phoneCode: "+47", arabicName: "النرويج"),
        CountryInfo(countryCode: "AT", phoneCode: "+43", arabicName: "النمسا"),
        CountryInfo(countryCode: "NE", phoneCode: "+227", arabicName: "النيجر"),
        CountryInfo(countryCode: "IN", phoneCode: "+91", arabicName: "الهند"),
        CountryInfo(countryCode: "US", phoneCode: "+1", arabicName: "الولايات المتحدة الأمريكيّة"),
        CountryInfo(countryCode: "JP", phoneCode: "+81", arabicName: "اليابان"),
        CountryInfo(countryCode: "YE", phoneCode: "+967", arabicName: "اليمن"),
        CountryInfo(countryCode: "GR", phoneCode: "+30", arabicName: "اليونان"),
        CountryInfo(countryCode: "PG", phoneCode: "+675", arabicName: "بابوا غينيا الجديدة"),
        CountryInfo(countryCode: "PY", phoneCode: "+595", arabicName: "باراغواي"),
        CountryInfo(countryCode: "PK", phoneCode: "+92", arabicName: "باكستان"),
        CountryInfo(countryCode: "PW", phoneCode: "+680", arabicName: "بالاو"),
        CountryInfo(countryCode: "BB", phoneCode: "+1-246", arabicName: "بربادوس"),
        CountryInfo(countryCode: "BM", phoneCode: "+1-441", arabicName: "برمودا"),
        CountryInfo(countryCode: "BN", phoneCode: "+673", arabicName: "بروني دار السلام"),
        CountryInfo(countryCode: "BE", phoneCode: "+32", arabicName: "بلجيكا"),
        CountryInfo(countryCode: "BG", phoneCode: "+359", arabicName: "بلغاريا"),
        CountryInfo(countryCode: "BZ", phoneCode: "+501", arabicName: "بليز"),
        CountryInfo(countryCode: "BD", phoneCode: "+880", arabicName: "بنغلاديش"),
        CountryInfo(countryCode: "PA", phoneCode: "+507", arabicName: "بنما"),
        CountryInfo(countryCode: "BJ", phoneCode: "+229", arabicName: "بنين"),
        CountryInfo(countryCode: "BT", phoneCode: "+975", arabicName: "بوتان"),
        CountryInfo(countryCode: "BW", phoneCode: "+267", arabicName: "بوتسوانا"),
        CountryInfo(countryCode: "BF", phoneCode: "+226", arabicName: "بوركينا فاسو"),
        CountryInfo(countryCode: "BI", phoneCode: "+257", arabicName: "بوروندي"),
        CountryInfo(countryCode: "PR", phoneCode: "+1", arabicName: "بورتو ريكو"),
        CountryInfo(countryCode: "PL", phoneCode: "+48", arabicName: "بولندا"),
        CountryInfo(countryCode: "BO", phoneCode: "+591", arabicName: "بوليفيا"),
        CountryInfo(countryCode: "PF", phoneCode: "+689", arabicName: "بولينيزيا الفرنسية"),
        CountryInfo(countryCode: "BQ", phoneCode: "+599", arabicName: "بونير وسينت أوستاتيوس وسابا"),
        CountryInfo(countryCode: "PN", phoneCode: "+64", arabicName: "بيتكيرن"),
        CountryInfo(countryCode: "PE", phoneCode: "+51", arabicName: "بيرو"),
        CountryInfo(countryCode: "BY", phoneCode: "+375", arabicName: "بيلاروس"),
        CountryInfo(countryCode: "TH", phoneCode: "+66", arabicName: "تايلند"),
        CountryInfo(countryCode: "TW", phoneCode: "+886", arabicName: "تايوان"),
        CountryInfo(countryCode: "TM", phoneCode: "+993", arabicName: "تركمانستان"),
        CountryInfo(countryCode: "TR", phoneCode: "+90", arabicName: "تركيا"),
        CountryInfo(countryCode: "TT", phoneCode: "+1-868", arabicName: "ترينيداد وتوباغو"),
        CountryInfo(countryCode: "TD", phoneCode: "+235", arabicName: "تشاد"),
        CountryInfo(countryCode: "CZ", phoneCode: "+420", arabicName: "تشيكيا"),
        CountryInfo(countryCode: "TG", phoneCode: "+228", arabicName: "توغو"),
        CountryInfo(countryCode: "TV", phoneCode: "+688", arabicName: "توفالو"),
        CountryInfo(countryCode: "TK", phoneCode: "+690", arabicName: "توكيلاو"),
        CountryInfo(countryCode: "TN", phoneCode: "+216", arabicName: "تونس"),
        CountryInfo(countryCode: "TO", phoneCode: "+676", arabicName: "تونغا"),
        CountryInfo(countryCode: "TL", phoneCode: "+670", arabicName: "تيمور - ليشتي"),
        CountryInfo(countryCode: "JM", phoneCode: "+1-876", arabicName: "جامايكا"),
        CountryInfo(countryCode: "GI", phoneCode: "+350", arabicName: "جبل طارق"),
        CountryInfo(countryCode: "BS", phoneCode: "+1-242", arabicName: "جزر البهاما"),
        CountryInfo(countryCode: "KM", phoneCode: "+269", arabicName: "جزر القمر"),
        CountryInfo(countryCode: "UM", phoneCode: "+1", arabicName: "جزر الولايات المتحدة الصغيرة النائية"),
        CountryInfo(countryCode: "TC", phoneCode: "+1-649", arabicName: "جزر تركس وكايكوس"),
        CountryInfo(countryCode: "SB", phoneCode: "+677", arabicName: "جزر سليمان"),
        CountryInfo(countryCode: "FK", phoneCode: "+500", arabicName: "جزر فوكلاند"),
        CountryInfo(countryCode: "VI", phoneCode: "+1-340", arabicName: "جزر فيرجن الأمريكية"),
        CountryInfo(countryCode: "VG", phoneCode: "+1-284", arabicName: "جزر فيرجن البريطانية"),
        CountryInfo(countryCode: "FO", phoneCode: "+298", arabicName: "جزر فيرويه"),
        CountryInfo(countryCode: "KY", phoneCode: "+1-345", arabicName: "جزر كايمان"),
        CountryInfo(countryCode: "CK", phoneCode: "+682", arabicName: "جزر كوك"),
        CountryInfo(countryCode: "CC", phoneCode: "+61", arabicName: "جزر كوكوس"),
        CountryInfo(countryCode: "MH", phoneCode: "+692", arabicName: "جزر مارشال"),
        CountryInfo(countryCode: "MP", phoneCode: "+1-670", arabicName: "جزر مريانا الشمالية"),
        CountryInfo(countryCode: "AX", phoneCode: "+358", arabicName: "جزر أولاند"),
        CountryInfo(countryCode: "IM", phoneCode: "+44-1624", arabicName: "جزيرة آيل أوف مان"),
        CountryInfo(countryCode: "GP", phoneCode: "+590", arabicName: "جزر وادي اللُّبّ"),
        CountryInfo(countryCode: "CX", phoneCode: "+61", arabicName: "جزيرة الكريسماس"),
        CountryInfo(countryCode: "BV", phoneCode: "+47", arabicName: "جزيرة بوفيه"),
        CountryInfo(countryCode: "NF", phoneCode: "+672", arabicName: "جزيرة نورفولك"),
        CountryInfo(countryCode: "HM", phoneCode: "+672", arabicName: "جزيرة هيرد وجزر ماكدونالد"),
        CountryInfo(countryCode: "RE", phoneCode: "+262", arabicName: "جمع شمل"),
        CountryInfo(countryCode: "CF", phoneCode: "+236", arabicName: "جمهوريّة أفريقيا الوسطى"),
        CountryInfo(countryCode: "CD", phoneCode: "+243", arabicName: "جمهوريّة الكونغو الديمقراطية"),
        CountryInfo(countryCode: "DO", phoneCode: "+1", arabicName: "جمهورية الدومينيكان"),
        CountryInfo(countryCode: "TZ", phoneCode: "+255", arabicName: "جمهوريّة تنزانيا المتحدة"),
        CountryInfo(countryCode: "KR", phoneCode: "+82", arabicName: "جمهوريّة كوريا"),
        CountryInfo(countryCode: "KP", phoneCode: "+850", arabicName: "جمهوريّة كوريا الشعبيّة الديمقراطية"),
        CountryInfo(countryCode: "LA", phoneCode: "+856", arabicName: "جمهوريّة لاو الديمقراطية الشعبيّة"),
        CountryInfo(countryCode: "MK", phoneCode: "+389", arabicName: "جمهوريّة مقدونيا اليوغوسلافية السابقة"),
        CountryInfo(countryCode: "MD", phoneCode: "+373", arabicName: "جمهوريّة مولدوفا"),
        CountryInfo(countryCode: "ZA", phoneCode: "+27", arabicName: "جنوب أفريقيا"),
        CountryInfo(countryCode: "SS", phoneCode: "+211", arabicName: "جنوب السودان"),
        CountryInfo(countryCode: "GE", phoneCode: "+995", arabicName: "جورجيا"),
        CountryInfo(countryCode: "GS", phoneCode: "+500", arabicName: "جورجيا الجنوبية وجزر ساندويتش الجنوبية"),
        CountryInfo(countryCode: "DJ", phoneCode: "+253", arabicName: "جيبوتي"),
        CountryInfo(countryCode: "JE", phoneCode: "+44-1534", arabicName: "جيرسي"),
        CountryInfo(countryCode: "DM", phoneCode: "+1-767", arabicName: "دومينيكا"),
        CountryInfo(countryCode: "RW", phoneCode: "+250", arabicName: "رواندا"),
        CountryInfo(countryCode: "RO", phoneCode: "+40", arabicName: "رومانيا"),
        CountryInfo(countryCode: "ZM", phoneCode: "+260", arabicName: "زامبيا"),
        CountryInfo(countryCode: "ZW", phoneCode: "+263", arabicName: "زمبابوي"),
        CountryInfo(countryCode: "WS", phoneCode: "+685", arabicName: "ساموا"),
        CountryInfo(countryCode: "AS", phoneCode: "+1-684", arabicName: "ساموا الأمريكية"),
        CountryInfo(countryCode: "PM", phoneCode: "+508", arabicName: "سان بيار وميكلون"),
        CountryInfo(countryCode: "ST", phoneCode: "+239", arabicName: "سان تومي وبرنسيبي"),
        CountryInfo(countryCode: "SM", phoneCode: "+378", arabicName: "سان مارينو"),
        CountryInfo(countryCode: "BL", phoneCode: "+590", arabicName: "سانت بارتيليمي"),
        CountryInfo(countryCode: "VC", phoneCode: "+1-784", arabicName: "سانت فنسنت وجزر غرينادين"),
        CountryInfo(countryCode: "KN", phoneCode: "+1-869", arabicName: "سانت كيتس ونيفيس"),
        CountryInfo(countryCode: "LC", phoneCode: "+1-758", arabicName: "سانت لوسيا"),
        CountryInfo(countryCode: "MF", phoneCode: "+590", arabicName: "سانت مارتن"),
        CountryInfo(countryCode: "SH", phoneCode: "+290", arabicName: "سانت هيلينا"),
        CountryInfo(countryCode: "LK", phoneCode: "+94", arabicName: "سري لانكا"),
        CountryInfo(countryCode: "SJ", phoneCode: "+47", arabicName: "سفالبارد وجان مايان"),
        CountryInfo(countryCode: "SK", phoneCode: "+421", arabicName: "سلوفاكيا"),
        CountryInfo(countryCode: "SI", phoneCode: "+386", arabicName: "سلوفينيا"),
        CountryInfo(countryCode: "SG", phoneCode: "+65", arabicName: "سنغافورة"),
        CountryInfo(countryCode: "SZ", phoneCode: "+268", arabicName: "سوازيلند"),
        CountryInfo(countryCode: "SY", phoneCode: "+963", arabicName: "سوريا"),
        CountryInfo(countryCode: "SR", phoneCode: "+597", arabicName: "سورينام"),
        CountryInfo(countryCode: "CH", phoneCode: "+41", arabicName: "سويسرا"),
        CountryInfo(countryCode: "SL", phoneCode: "+232", arabicName: "سيراليون"),
        CountryInfo(countryCode: "SC", phoneCode: "+248", arabicName: "سيشيل"),
        CountryInfo(countryCode: "CL", phoneCode: "+56", arabicName: "شيلي"),
        CountryInfo(countryCode: "RS", phoneCode: "+381", arabicName: "صربيا"),
        CountryInfo(countryCode: "TJ", phoneCode: "+992", arabicName: "طاجيكستان"),
        CountryInfo(countryCode: "OM", phoneCode: "+968", arabicName: "عمان"),
        CountryInfo(countryCode: "GA", phoneCode: "+241", arabicName: "غابون"),
        CountryInfo(countryCode: "GM", phoneCode: "+220", arabicName: "غامبيا"),
        CountryInfo(countryCode: "GH", phoneCode: "+233", arabicName: "غانا"),
        CountryInfo(countryCode: "GD", phoneCode: "+1-473", arabicName: "غرينادا"),
        CountryInfo(countryCode: "GT", phoneCode: "+502", arabicName: "غواتيمالا"),
        CountryInfo(countryCode: "GU", phoneCode: "+1-671", arabicName: "غوام"),
        CountryInfo(countryCode: "GF", phoneCode: "+594", arabicName: "غويانا الفرنسية"),
        CountryInfo(countryCode: "GY", phoneCode: "+592", arabicName: "غيانا"),
        CountryInfo(countryCode: "GG", phoneCode: "+44-1481", arabicName: "غيرنسي"),
        CountryInfo(countryCode: "GN", phoneCode: "+224", arabicName: "غينيا"),
        CountryInfo(countryCode: "GW", phoneCode: "+245", arabicName: "غينيا - بيساو"),
        CountryInfo(countryCode: "GQ", phoneCode: "+240", arabicName: "غينيا الاستوائيّة"),
        CountryInfo(countryCode: "VU", phoneCode: "+678", arabicName: "فانواتو"),
        CountryInfo(countryCode: "FR", phoneCode: "+33", arabicName: "فرنسا"),
        CountryInfo(countryCode: "PS", phoneCode: "+970", arabicName: "فلسطين"),
        CountryInfo(countryCode: "VE", phoneCode: "+58", arabicName: "فنزويلا"),
        CountryInfo(countryCode: "FI", phoneCode: "+358", arabicName: "فنلندا"),
        CountryInfo(countryCode: "FJ", phoneCode: "+679", arabicName: "فيجي"),
        CountryInfo(countryCode: "VN", phoneCode: "+84", arabicName: "فييت نام"),
        CountryInfo(countryCode: "CY", phoneCode: "+357", arabicName: "قبرص"),
        CountryInfo(countryCode: "QA", phoneCode: "+974", arabicName: "قطر"),
        CountryInfo(countryCode: "KG", phoneCode: "+996", arabicName: "قيرغيزستان"),
        CountryInfo(countryCode: "CV", phoneCode: "+238", arabicName: "كابو فيردي"),
        CountryInfo(countryCode: "KZ", phoneCode: "+7", arabicName: "كازاخستان"),
        CountryInfo(countryCode: "NC", phoneCode: "+687", arabicName: "كاليدونيا الجديدة"),
        CountryInfo(countryCode: "HR", phoneCode: "+385", arabicName: "كرواتيا"),
        CountryInfo(countryCode: "KH", phoneCode: "+855", arabicName: "كمبوديا"),
        CountryInfo(countryCode: "CA", phoneCode: "+1", arabicName: "كندا"),
        CountryInfo(countryCode: "CU", phoneCode: "+53", arabicName: "كوبا"),
        CountryInfo(countryCode: "CI", phoneCode: "+225", arabicName: "كوت ديفوار"),
        CountryInfo(countryCode: "CW", phoneCode: "+599", arabicName: "كوراكاو"),
        CountryInfo(countryCode: "CR", phoneCode: "+506", arabicName: "كوستاريكا"),
        CountryInfo(countryCode: "CO", phoneCode: "+57", arabicName: "كولومبيا"),
        CountryInfo(countryCode: "KI", phoneCode: "+686", arabicName: "كيريباس"),
        CountryInfo(countryCode: "KE", phoneCode: "+254", arabicName: "كينيا"),
        CountryInfo(countryCode: "LV", phoneCode: "+371", arabicName: "لاتفيا"),
        CountryInfo(countryCode: "LB", phoneCode: "+961", arabicName: "لبنان"),
        CountryInfo(countryCode: "LU", phoneCode: "+352", arabicName: "لكسمبرغ"),
        CountryInfo(countryCode: "LR", phoneCode: "+231", arabicName: "ليبريا"),
        CountryInfo(countryCode: "LY", phoneCode: "+218", arabicName: "ليبيا"),
        CountryInfo(countryCode: "LT", phoneCode: "+370", arabicName: "ليتوانيا"),
        CountryInfo(countryCode: "LI", phoneCode: "+423", arabicName: "ليختنشتاين"),
        CountryInfo(countryCode: "LS", phoneCode: "+266", arabicName: "ليسوتو"),
        CountryInfo(countryCode: "MQ", phoneCode: "+596", arabicName: "مارتينيك"),
        CountryInfo(countryCode: "MO", phoneCode: "+853", arabicName: "ماكاو"),
        CountryInfo(countryCode: "MT", phoneCode: "+356", arabicName: "مالطة"),
        CountryInfo(countryCode: "ML", phoneCode: "+223", arabicName: "مالي"),
        CountryInfo(countryCode: "MY", phoneCode: "+60", arabicName: "ماليزيا"),
        CountryInfo(countryCode: "YT", phoneCode: "+262", arabicName: "مايوت"),
        CountryInfo(countryCode: "MG", phoneCode: "+261", arabicName: "مدغشقر"),
        CountryInfo(countryCode: "EG", phoneCode: "+20", arabicName: "مصر"),
        CountryInfo(countryCode: "MW", phoneCode: "+265", arabicName: "ملاوي"),
        CountryInfo(countryCode: "MV", phoneCode: "+960", arabicName: "ملديف"),
        CountryInfo(countryCode: "MN", phoneCode: "+976", arabicName: "منغوليا"),
        CountryInfo(countryCode: "MR", phoneCode: "+222", arabicName: "موريتانيا"),
        CountryInfo(countryCode: "MU", phoneCode: "+230", arabicName: "موريشيوس"),
        CountryInfo(countryCode: "MZ", phoneCode: "+258", arabicName: "موزامبيق"),
        CountryInfo(countryCode: "MC", phoneCode: "+377", arabicName: "موناكو"),
        CountryInfo(countryCode: "MS", phoneCode: "+1-664", arabicName: "مونتسيرات"),
        CountryInfo(countryCode: "MM", phoneCode: "+95", arabicName: "ميانمار"),
        CountryInfo(countryCode: "FM", phoneCode: "+691", arabicName: "ميكرونيزيا"),
        CountryInfo(countryCode: "NA", phoneCode: "+264", arabicName: "ناميبيا"),
        CountryInfo(countryCode: "NR", phoneCode: "+674", arabicName: "ناورو"),
        CountryInfo(countryCode: "NP", phoneCode: "+977", arabicName: "نيبال"),
        CountryInfo(countryCode: "NG", phoneCode: "+234", arabicName: "نيجيريا"),
        CountryInfo(countryCode: "NI", phoneCode: "+505", arabicName: "نيكاراغوا"),
        CountryInfo(countryCode: "NZ", phoneCode: "+64", arabicName: "نيوزيلندا"),
        CountryInfo(countryCode: "NU", phoneCode: "+683", arabicName: "نيوي"),
        CountryInfo(countryCode: "HT", phoneCode: "+509", arabicName: "هايتي"),
        CountryInfo(countryCode: "HN", phoneCode: "+504", arabicName: "هندوراس"),
        CountryInfo(countryCode: "HU", phoneCode: "+36", arabicName: "هنغاريا"),
        CountryInfo(countryCode: "NL", phoneCode: "+31", arabicName: "هولندا"),
        CountryInfo(countryCode: "HK", phoneCode: "+852", arabicName: "هونغ كونغ"),
        CountryInfo(countryCode: "WF", phoneCode: "+681", arabicName: "واليس وفوتونا"),
    ]

}
